spring:
  application:
    name: challenge
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${CLEARDB_DATABASE_URL}

    url: ${CLEARDB_DATABASE_URL}

  liquibase:
    change-log: 'classpath:db/changelog/liquibase-changelog.xml'
server:
  servlet:
    context-path: /users
