spring:
  application:
    name: challenge
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${JAWSDB_URL}
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: true
      minimum-idle: 5
      idle-timeout: 30000

    url: ${JAWSDB_URL}

  liquibase:
    change-log: 'classpath:db/changelog/liquibase-changelog.xml'
server:
  servlet:
    context-path: /users
