spring:
  application:
    name: challenge
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/challenge
      username: root
      password: root

    url: jdbc:mysql://localhost:3306/challenge

  liquibase:
    change-log: 'classpath:db/changelog/liquibase-changelog.xml'
server:
  servlet:
    context-path: /users
